language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install --yes nodejs
  - npm install -g grunt-cli

install:
  - npm install
  - composer install

script:
  - grunt

after_script:
  - php vendor/bin/coveralls -v
  - chmod +x code-climate-test-reporter
  - CODECLIMATE_REPO_TOKEN=22f651c22e953865509abf9a97b48de2909e3d03e48f7d50ceb332082b278c81 ./code-climate-test-reporter
